version: '3.3'
services:
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  api:
    build: ./backend
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
  fe:
    build: ./frontend
    ports:
      - 3000:3000
  db:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=nude1234!!
      - MYSQL_DATABASE=nude
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - nude_mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  nude_mysql_db: {}