export const APP_LAYOUT_PADDING = 20;
export const BOTTOM_NAVIGATION_BAR_HEIGHT = 60;
export const MOBILE_HEADER_HEIGHT = 64;
export const P_HEADER_PADDING_TOP = 60;
export const APP_BAR_HEIGHT = 44;

export enum ZIndexes {
  BACKGROUND_VIDEO = -1,
  COLLECTION_VIDEO = 1,
  BOTTOM_SHEET = 90,
  BOTTOM_SHEET_CONTENT = 91,
  MOBILE_HEADER = 99,
  BOTTOM_NAVIGATION_BAR = 99,
  FULL_SCREEN = 100,
  HIGHLIGHT = 101,
}
