name: Build And Deploy Code
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Docker Image Build For BackEnd
        run: |
          git pull
          git checkout main
          ./script/be-build.sh

      - name: Docker Image Build For FrontEnd
        run: |
          git pull
          git checkout main
          ./script/fe-build.sh